### ISSUE TITLE
salut 

### ISSUE THREAD

**Issue by cybermandiant** [InnoGreenTech/Home_controller#1]
salut super beau projet seulement je bloque sur la librairie manquante  <Fonts/WeatherIcon.h>
dans le dossier Main board le croqui ne veux pas ce compiler :( car il manque ce fichier

**Comment by InnoGreenTech** [comment]
Bonjour, 
Il faut récupérer le font ici: https://github.com/kaldoran/Adafruit-Weather-Icon/blob/master/WeatherIcon.h  Ensuite installer le fichier sous le répertoire Adafruit_GFX_Library\Fonts de la bibliothèque d'Ada-fruit.

**Comment by cybermandiant** [comment]
Bonsoir super merci beaucoup pour la reponse :)
